sudo: required

services:
    - docker

env:
    - distribution: cern/slc6-base
      distribution_name: slc6-base
      version: latest
    - distribution: centos
      distribution_name: centos
      version: 7

before_install:
    - docker pull ${distribution}:${version}
    - docker build --file=travis/Dockerfile.${distribution_name}-${version} --tag=${distribution_name}-${version}:threadmon-task-build travis

script:
    - container_id=$(mktemp)
    - docker run -d --privileged --volume="${PWD}":/threadmon-task ${distribution_name}-${version}:threadmon-task-build tail -f /dev/null > "${container_id}"
    # Build
    - docker exec "$(cat ${container_id})" bash -c "cd /threadmon-task; mkdir build; cd build; cmake .. && make"